(function ($) {
$.Redactor.opts.langs['fr'] = {
	html: 'Code HTML',
	video: 'Ins&eacute;rer une vid&eacute;o...',
	image: 'Ins&eacute;rer une image...',
	table: 'Tableau',
	link: 'Lien',
	link_insert: 'Ins&eacute;rer un lien...',
	link_edit: 'Modifier le lien',
	unlink: 'Supprimer le lien',
	formatting: 'Styles',
	paragraph: 'Paragraphe',
	quote: 'Citation',
	code: 'Code',
	header1: 'Titre 1',
	header2: 'Titre 2',
	header3: 'Titre 3',
	header4: 'Titre 4',
	header5: 'Titre 5',
	bold:  'Gras',
	italic: 'Italique',
	fontcolor: 'Couleur du texte',
	backcolor: 'Couleur d\'arri&egrave;re plan du texte',
	unorderedlist: 'Liste &agrave; puces',
	orderedlist: 'Liste num&eacute;rot&eacute;e',
	outdent: 'Diminuer le retrait',
	indent: 'Augmenter le retrait',
	cancel: 'Annuler',
	insert: 'Ins&eacute;rer',
	save: 'Enregistrer',
	_delete: 'Supprimer',
	insert_table: 'Ins&eacute;rer un tableau...',
	insert_row_above: 'Ajouter une rang&eacute;e au-dessus',
	insert_row_below: 'Ajouter une rang&eacute;e en-dessous',
	insert_column_left: 'Ajouter une colonne &agrave; gauche',
	insert_column_right: 'Ajouter une colonne &agrave; droite',
	delete_column: 'Supprimer la colonne',
	delete_row: 'Supprimer la rang&eacute;e',
	delete_table: 'Supprimer le tableau',
	rows: 'Rang&eacute;es',
	columns: 'Colonnes',
	add_head: 'Ajouter un en-tête',
	delete_head: 'Supprimer l\'en-tête',
	title: 'Titre',
	image_position: 'Position',
	none: 'Aucun',
	left: 'Gauche',
	right: 'Droite',
	image_web_link: 'Adresse URL de l\'image',
	text: 'Texte',
	mailto: 'Courriel',
	web: 'Adresse URL',
	video_html_code: 'Code d\'int&eacute;gration du video',
	file: 'Ins&eacute;rer un fichier...',
	upload: 'T&eacute;l&eacute;verser',
	download: 'T&eacute;l&eacute;charger',
	choose: 'Choisir',
	or_choose: 'Ou choisissez',
	drop_file_here: 'D&eacute;posez le fichier ici',
	align_left:	'Aligner &agrave; gauche',
	align_center: 'Aligner au centre',
	align_right: 'Aligner &agrave; droite',
	align_justify: 'Justifier',
	horizontalrule: 'Ins&eacute;rer une ligne horizontale',
	deleted: 'Supprim&eacute;',
	anchor: 'Ancre',
	link_new_tab: 'Ouvrir le lien dans un nouvel onglet',
	underline: 'Souligner',
	alignment: 'Alignement',
	filename: 'Nom de fichier (optionnel)',
	edit: 'Edit'
};
})( jQuery );